//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Project_8th_Module.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int BookID { get; set; }
        public string BookTitle { get; set; }
        public string ISBN { get; set; }
        public Nullable<int> AuthorID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> NoOfPage { get; set; }
        public Nullable<int> PublisherID { get; set; }
        public string ImageUrl { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Department Department { get; set; }
        public virtual Publisher Publisher { get; set; }
    }
}
